// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TallerNet8.Contexto;

#nullable disable

namespace TallerNet8.Migrations
{
    [DbContext(typeof(TallerNet8DBContext))]
    [Migration("20240621014448_primeraMigracion")]
    partial class primeraMigracion
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TallerNet8.Dto.Alumno", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nivel")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("Id");

                    b.ToTable("Alumno", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nivel = "Primaria",
                            Nombre = "Juan"
                        },
                        new
                        {
                            Id = 2,
                            Nivel = "Primaria",
                            Nombre = "Miguel"
                        },
                        new
                        {
                            Id = 3,
                            Nivel = "Primaria",
                            Nombre = "Luis"
                        },
                        new
                        {
                            Id = 4,
                            Nivel = "Primaria",
                            Nombre = "Manuel"
                        });
                });

            modelBuilder.Entity("TallerNet8.Dto.BoletaNotas", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("AlumnoId")
                        .HasColumnType("int");

                    b.Property<int>("CursoId")
                        .HasColumnType("int");

                    b.Property<int>("nota1")
                        .HasColumnType("int");

                    b.Property<int>("nota2")
                        .HasColumnType("int");

                    b.Property<int>("nota3")
                        .HasColumnType("int");

                    b.Property<int>("promedio")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AlumnoId");

                    b.HasIndex("CursoId");

                    b.ToTable("BoletaNotas", (string)null);
                });

            modelBuilder.Entity("TallerNet8.Dto.Curso", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Profesor")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("Id");

                    b.ToTable("Curso", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nombre = "Matematica",
                            Profesor = "Juanito Perez"
                        },
                        new
                        {
                            Id = 2,
                            Nombre = "Comunicacion",
                            Profesor = "Juanito H"
                        },
                        new
                        {
                            Id = 3,
                            Nombre = "Ingles",
                            Profesor = "Juanito Quispe"
                        });
                });

            modelBuilder.Entity("TallerNet8.Dto.BoletaNotas", b =>
                {
                    b.HasOne("TallerNet8.Dto.Alumno", "alumno")
                        .WithMany()
                        .HasForeignKey("AlumnoId");

                    b.HasOne("TallerNet8.Dto.Curso", "curso")
                        .WithMany()
                        .HasForeignKey("CursoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("alumno");

                    b.Navigation("curso");
                });
#pragma warning restore 612, 618
        }
    }
}
